### ISSUE TITLE
View Devices opens inspect tab

### ISSUE THREAD

**Issue by stefanhoth** [googlearchive/ADBPlugin#12]
The adb plugin starts up just fine and even showed a little "1" when I started an emulator.

But the "View Devices" entry just opens the "inspect" tab. Shouldn't there be a list of attached devices or sth?

OS: Windows 7
Chrome: stable, 27

**Comment by paulirish** [comment]
@stefanhoth make sure you turn on the USB debugging settings for both Android and Chrome 
https://developers.google.com/chrome-developer-tools/docs/remote-debugging#enable-usb-debugging

**Comment by stefanhoth** [comment]
I checked the settings and all is fine. The devices seem to be recognized (displaying nothing, 1 or 2 depending how many devices are connected) but "View Devices" still leads me to the inspect tab. I tested with emulators as well as real devices.

What I'm doing wrong?

**Comment by samhed** [comment]
The instructions at https://developers.google.com/chrome-developer-tools/docs/remote-debugging indicates that "View Devices" is intended to open the inspect tab. A quote from the instructions:

"Click View Devices to open the chrome://inspect page that displays each connected device and its tabs.
Find the mobile device tab you want to debug and Click the inspect link next to its URL."

I do not believe this is a bug or that you are doing anything wrong.

**Comment by stefanhoth** [comment]
Ok, sorry. It's a bit confusing as I would have expected to have a more clear view on debug-able pages from my mobile devices.
Thanks for clearing this up.

**Comment by paulirish** [comment]
I'll leave this open for now. I can update the text of the extension to be a bit more clear.

**Comment by paulirish** [comment]
tweaked wording and added link to help:

![image](https://f.cloud.github.com/assets/39191/785826/2b127cbe-ea90-11e2-91f3-8d6f9ae43e6b.png)
