### ISSUE TITLE
The plugin doesn't start. Linux.

### ISSUE THREAD

**Issue by samhed** [googlearchive/ADBPlugin#13]
I just installed the ADBPlugin (0.9.6) in Chrome (Version 28.0.1500.89 beta) ran on Fedora 18. Nothing happens when I click "Start ADB" in the ADB dropdown menu in chrome. The log shows the following:

/home/samuel/.config/google-chrome/Default/Extensions/dpngiggdglpdnjdoaefidgiigpemgage/0.9.6_0/linux/adb: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

**Comment by samhed** [comment]
I just now installed the Android Debug Bridge via yum, this made the "Start ADB" button work but I am now experiencing new problems. Discussing those in other issues.

The documentation at https://developers.google.com/chrome-developer-tools/docs/remote-debugging which led me to use this plugin does not specify that the command line adb program is required. I get the impression that this plugin should be somewhat stand alone?

Edit: Your own README.md says: "With it, you do not need to download the Android SDK or run ADB yourself from the command line. "

**Comment by paulirish** [comment]
@samhed Indeed. If working successfully.. the extension should not require you to install the adb binary. It's a bug! :)

Thanks very much for reporting.. the error message in particular.

**Comment by sfate** [comment]
@samhed seems in general you just need to install `libncurses5` package.
For fedora: `yum install libncurses5`

**Comment by paulirish** [comment]
you can also install the `ia32-libs` package which will include libncurses.

**Comment by paulirish** [comment]
I've just added this to the docs. We've decided to not bundle linbcurses with the extension. the package installation will be required.  

Thanks for reporting!
