### ISSUE TITLE
The webpage to be inspected was not shown in Developer Tools

### ISSUE THREAD

**Issue by qsu** [googlearchive/ADBPlugin#16]
"chome_stable+ADBcmd" for remote debugging works fine.
I have tried "chrome_beta+ADBPlugin" both on windows7 and ubuntu. After clicking the inspect link, the window of Developer Tools will be popped out, but the content of "Elements" will always be like following content no matter what page is shown on my Android device.
//
//<!DOCTYPE html>
//<_html>
//<_head></_head>"
//  <_body>
//    <_object type="application/x-adbplugin" id="adb-plugin"></object>
//    <_script type="text/javascript" src="background.js"></script>
//  </_body>
//</_html>

Did I use it in a wrong way?

**Comment by paulirish** [comment]
you seem to be inspecting the background page of the ADB chrome extension, rather than the page on your device.
