### ISSUE TITLE
to exec "xcodebuild ARCHS=i386 ONLY_ACTIVE_ARCH=NO -configuration Release -project build/FireBreath.xcodeproj"  Error  on the imac

### ISSUE THREAD

**Issue by 899** [googlearchive/ADBPlugin#18]
=== BUILD NATIVE TARGET ADBPlugin OF PROJECT FireBreath WITH CONFIGURATION Release ===
Check dependencies

PhaseScriptExecution "CMake PostBuild Rules" build/projects/ADBPlugin/FireBreath.build/Release/ADBPlugin.build/Script-D133E8809F0F4511A3DB9C19.sh
    cd /Users/ethan/Downloads/firebreath
    /bin/sh -c /Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/FireBreath.build/Release/ADBPlugin.build/Script-D133E8809F0F4511A3DB9C19.sh
/bin/cp -r /Users/ethan/Downloads/firebreath/projects/ADBPlugin/Chrome/chromepackage/\* /Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/gen/npADBPlugin-crx
/bin/cp -r /Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/Release/npADBPlugin.plugin /Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/gen/npADBPlugin-crx
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension="/Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/gen/npADBPlugin-crx" --pack-extension-key="/Users/ethan/Downloads/firebreath/projects/ADBPlugin/sign/dummy_key.pem" --no-message-box
无法加载插件的路径“/Users/ethan/Downloads/firebreath/build/projects/ADBPlugin/gen/npADBPlugin-crx/npADBPlugin.dll”。
make: **\* [ADBPlugin_buildpart_1] Error 21
Command /bin/sh failed with exit code 2

*\* BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution "CMake PostBuild Rules" build/projects/ADBPlugin/FireBreath.build/Release/ADBPlugin.build/Script-D133E8809F0F4511A3DB9C19.sh
(1 failure)

**Comment by adam-singer** [comment]
You can just copy and paste the `firebreath/projects/out/npADBPlugin.dll` into `firebreathbuild/projects/ADBPlugin/gen/npADBPlugin-crx/npADBPlugin.dll` and re ran the build scripts. The .dll is not built by the scripts anyway so you should be safe if your working with this on Mac.

**Comment by paulirish** [comment]
We're now deprecating the extension, so we likely will not be updating the build scripts.
