### ISSUE TITLE
ADB Extension does not install!

### ISSUE THREAD

**Issue by NathanDaugherty** [googlearchive/ADBPlugin#23]
No matter how many times I re-attempt, re-start, etc, the extension for ADB will not install. It keeps giving me "An error has occurred" pop up. I am on Windows 7 using Chrome 22. Any help appreciated!

**Comment by mraffaele** [comment]
The documentation states that to start debugging, you need: "Chrome 28 or later installed on your development machine."

https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging

**Comment by paulirish** [comment]
We're now deprecating this extension. 

Chrome now has full built-in support for remote debugging so the extension is no longer neccessary. 

All the details are updated here: https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging ☜

(If that doesnt work for you, fall back to the using the [adb binary](https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy))
