### ISSUE TITLE
Crashes in Windows 8.1

### ISSUE THREAD

**Issue by varemenos** [googlearchive/ADBPlugin#24]
Visiting the `chrome://inspect` page's Device tab crashes the browser

Using Windows 8.1 x64, Chrome 30
Tried on 2 devices HP Touchpad (ICS), Archos Platinum 50 (JB)

**Comment by bradyemerson** [comment]
+1... Chrome 30, ADB v0.9.3.  Samsung SIII with Chrome Beta 31

**Comment by drsouly** [comment]
+1 "Chrome30.0.1599.101 m" with nexus5

**Comment by blowsie** [comment]
+1

Crashes on     `32.0.1700.107 m` with "Galaxy Tab 3 10.1"
Works fine on `32.0.1700.107 m` with "Samsung Note 2"

#### Update

This was being caused by a non branded USB cable!!!

**Comment by paulirish** [comment]
I believe this is resolved. There should not be any more crashes.
