### ISSUE TITLE
Can't install extension on Chrome 30/Win 8

### ISSUE THREAD

**Issue by acidr4in1** [googlearchive/ADBPlugin#26]
Hi,

I can't even click on the download Icon. It says something like: "This application is not supported on this computer. The installation was deactivated."

Why should my PC not be supported.

Running
Chrome 30
Win 8 64-Bit

Edit Sorry my bad just saw the the solution on the main page.
Would be great to add this in the app discripton.

**Comment by Elsworth** [comment]
Would you be able to list how you solved this?  I don't know which main page you're referring to.

**Comment by acidr4in1** [comment]
The Projects Main Page
https://github.com/GoogleChrome/ADBPlugin

"Windows 8: Unfortunately you cannot install from the Chrome Web Store. Right click and download this CRX file then open about:extensions in Chrome and drag the CRX onto that page to install. This extension will not automatically stay up to date."

**Comment by Elsworth** [comment]
Oh in github.  Thanks.

**Comment by bradyemerson** [comment]
Can anyone expand on why Win8 blocks the download/instillation from Chrome Web Store? Is it an issue with the plugin, something in chrome that is being worked on, or a restriction in Win8 that can't be worked around?

**Comment by paulirish** [comment]
Thanks very much for the detailed bug report, however we're now deprecating this extension. 

Chrome now has full built-in support for remote debugging so the extension is no longer neccessary. 

All the details are updated here: https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging ☜

(If that doesnt work for you, fall back to the using the [adb binary](https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy))
