### ISSUE TITLE
Clicking the gray icon does not bring up does not bring up start options 

### ISSUE THREAD

**Issue by buffala** [googlearchive/ADBPlugin#27]
I have ran adb devices and it list my connected device.  I can debug in eclipse and debug is enabled in Chrome on the device.  When I click on the gray adroid icon nothing happens.  The start and stop options do not list as in the instructions.  I am running windows 7.  with the latest chrome I am sure as it auto updates...  Any help getting adb started would be great...

**Comment by abathur** [comment]
I believe I'm seeing the same issue. I was suspecting it might've been caused by some new programs which are enabled at startup, but I've disabled these, uninstalled the plugin in both chrome/canary, rebooted and reinstalled the plugin and the behavior is the same.

**Comment by abathur** [comment]
I got this working again, for me at least. Just in case this helps someone else, I did:
1.) Computer management -> device manager -> SAMSUNG Android Phone -> SAMSUNG Android ADB Interface -> Uninstall
2.) Disconnect / reconnect phone, wait for driver to install
3.) Click ADB icon, which now works
