### ISSUE TITLE
New Chrome Extension Policy will Kill ADB Pluggin for Win8

### ISSUE THREAD

**Issue by WORMSS** [googlearchive/ADBPlugin#29]
As you may know. (Or not).. Google has made the decision to change the policy on installing Extensions in Chrome so you have to have an app in the webstore and install from there..
I don't want to go into why.
But just want to flag up the side effect of this is on Win8 where the Extension HAS to be loaded outside of the webstore. (Which obviously you do know since its on the main page).

Can someone who works at Google go over to the peeps who are doing this change and give them a quick Prod.. Remind them that this will effect their OWN extensions in a bad way.

**Comment by MiguelRipoll23** [comment]
Same here. I can't keep this extension from getting blocked!

**Comment by paulirish** [comment]
Very true @WORMSS. Thanks for writing up the detail and filing a ticket.

Chrome now has full built-in support for remote debugging so the extension is no longer neccessary. 

All the details are updated here: https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging ☜

(If that doesnt work for you, fall back to the using the [adb binary](https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy))

Using this extension, especially on Win8, is no longer going to work very well and I don't see that changing.
