### ISSUE TITLE
Devices list is empty, though the Android icon shows otherwise

### ISSUE THREAD

**Issue by mraffaele** [googlearchive/ADBPlugin#30]
As title states; my device list is showing up empty, yet the Android icon beside the address bar shows a little number 1 when I connect my device.

![screen shot 2013-11-14 at 12 23 11 pm](https://f.cloud.github.com/assets/3249275/1537669/876dd8b6-4ccc-11e3-903a-3eb7567ecd67.png)
## System settings:

Mac OSX (10.7.5)
Google Chrome (31.0.1650.48) - Also using official Glow theme.

Nexus 4 (16 gb) Running Android 4.3
Google Chrome for Android (30.0.1599.92)

Both Chrome for Android, and the device itself have USB Debugging Enabled & permission granted

**Comment by mraffaele** [comment]
As a side note, I installed Chrome Canary (33.0.1708.0) and it worked without changing any settings.

**Comment by paulirish** [comment]
Yup, things should be fine for this issue in Chrome 32+
