### ISSUE TITLE
"Start ADB" does not work, gives ncurses error

### ISSUE THREAD

**Issue by bryanlarsen** [googlearchive/ADBPlugin#31]
If I click on "Start ADB" it gives me the error:

```
 /home/blarsen/.config/google-chrome-beta/Default/Extensions/dpngiggdglpdnjdoaefidgiigpemgage/0.9.7_0/linux/adb: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

libncurses5-5.9+20130608-1ubuntu1 is installed on my machine.

I have to start adb manually at the command line by typing `adb devices`.   When I do that the icon turns green and everything works fine.

uname -a:  Linux ball 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Google Chrome   31.0.1650.48 (Official Build 233213) beta

ADB 0.9.7

**Comment by paulirish** [comment]
Hi Bryan,

Thanks very much for the detailed bug report, however we're now deprecating this extension. 

Chrome now has full built-in support for remote debugging so the extension is no longer neccessary. 

All the details are updated here: https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging ☜

(If that doesnt work for you, fall back to the using the [adb binary](https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy))
