### ISSUE TITLE
Is it possible to make this work with Amazon's Kindle devices?

### ISSUE THREAD

**Issue by ChrisWren** [googlearchive/ADBPlugin#34]
Just came across Amazon's docs for developing/debugging web apps, and was wondering if anyone knew if it would be possible to use this extension to debug a web app on a Kindle?

[Here](https://developer.amazon.com/sdk/webapps/debug-webapp.html) are the docs.

**Comment by paulirish** [comment]
They're using a different port.

So, you can use this extension to start/stop ADB, but you'll need to issue the adb forward command like they recommend and then all the subsequent instruction.s
