### ISSUE TITLE
Why is port forwarding limited to 1024-10000 range?

### ISSUE THREAD

**Issue by risujin** [googlearchive/ADBPlugin#35]
Port forwarding is a great feature but is limited by a seemingly arbitrary range restriction in Chrome:

``` js
function validatePort(input) {
  var match = input.value.match(/^(\d+)$/);
  if (!match)
    return false;
  var port = parseInt(match[1]);
  if (port < 1024 || 10000 < port) // ←←←←←←←←←←
    return false;
  ...
  return true;
}
```

Is there a reason for that? Can this be changed to allow all ports, or at least, ports above 10000?

**Comment by paulirish** [comment]
yes, this has now been updated!

http://src.chromium.org/viewvc/chrome?view=revision&revision=245151

Chrome 34 (currently dev channel and canary) support ports >10000
