### ISSUE TITLE
Extension is blocked if installed using Developer Mode

### ISSUE THREAD

**Issue by MiguelRipoll23** [googlearchive/ADBPlugin#36]
After installing the extension using the Windows 8 instructions from the README.md file and rebooting my computer, my extension got blocked because "it may be installed without my knowledge". I've tried to install it again, same happens.

![fix](https://f.cloud.github.com/assets/3296866/2181491/4a37c066-9753-11e3-9f31-4a0663e646fa.jpg)

**Comment by paulirish** [comment]
Chrome is now being pretty restrictive when it comes to NPAPI plugins, especially on Win8. 

I would recommend you drop this extension and go directly with the newish built-in support: https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging

If that doesnt work for you, fall back to the real adb binary: https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy

**Comment by MiguelRipoll23** [comment]
I'm gonna use the built-in support. I saw it on HTML5 Rocks, but I thought this plugin may be required so thank you!
