### ISSUE TITLE
Can I downgrade?

### ISSUE THREAD

**Issue by meobyte** [googlearchive/ADBPlugin#37]
The native Chrome debugger doesn't detect any of my devices. The ADB plugin used to worked just fine. I've spent my morning reinstalling USB drivers for my S4, Google Nexus and Nexus 7, rebooting everything and I just get "No devices detected."

I've tried it with 33.0.1750.117 m and 35.0.1858.0 canary on the desktop and 32.0.1700.99 on my devices. I'd rather not use the legacy way and install the sdk. I'd really just like to enable the ADB plugin and go about my work.

**Comment by paulirish** [comment]
Windows 8?

**Comment by meobyte** [comment]
Windows 7.

I did finally get it working. I went and got the sdk and ran adb devices. It said \* daemon not running. starting it now on port 5037 *, \* daemon started successfully \* and then listed my devices. I went back to Chrome and did Tools -> Inspect Devices, and everything was working as it used to.

**Comment by paulirish** [comment]
Thanks for the details here.. I've opened a ticket on the chromium tracker.. I'd love your help with any details you can offer: 
https://code.google.com/p/chromium/issues/detail?id=361856
