### ISSUE TITLE
No longer works with my VZ LG Spectrum 2

### ISSUE THREAD

**Issue by James1x0** [googlearchive/ADBPlugin#38]
Hooked up as ethernet with a usb, debugging enabled. Says debugging connected. Inspection targets does not show it. Tried multiple modes. My Nexus 7 works just fine. Help.

**Comment by paulirish** [comment]
Windows 7?

**Comment by James1x0** [comment]
Yep

**Comment by paulirish** [comment]
Thanks for the details here.. I've opened a ticket on the chromium tracker.. I'd love your help with any details you can offer: 
https://code.google.com/p/chromium/issues/detail?id=361856

**Comment by paulirish** [comment]
Does the legacy workflow (https://developers.google.com/chrome-developer-tools/docs/remote-debugging-legacy) work with the spectrum?

**Comment by paulirish** [comment]
@aehrJames you installed the drivers for the LG, can you confirm?
https://code.google.com/p/chromium/issues/detail?id=361856#c2

**Comment by James1x0** [comment]
Drivers are installed and did work with the old adb plugin/extension.
